-keep class ru.ytkab0bp.beamklipper.KlipperApp { *; }
-keep class ru.ytkab0bp.beamklipper.cloud.CloudAPI { *; }
-keep class ru.ytkab0bp.beamklipper.cloud.CloudAPI$* { *; }
-keep class ru.ytkab0bp.beamklipper.cloud.CloudController { *; }
